USE college2;

CREATE TABLE department(
did VARCHAR(3),
name VARCHAR(50) UNIQUE NOT NULL,
PRIMARY KEY(did)
);

CREATE TABLE teacher(
tid VARCHAR(3),
name VARCHAR(50) NOT NULL,
deptid VARCHAR(3) NOT NULL,
PRIMARY KEY(tid),
FOREIGN KEY(deptid) REFERENCES department(did)
ON DELETE CASCADE
ON UPDATE CASCADE
);