CREATE DATABASE IF NOT EXISTS dummyDB;
USE dummyDB;
CREATE TABLE dt1(
cid INT,
cname VARCHAR(50) NOT NULL,
cpassword VARCHAR(20) NOT NULL,
PRIMARY KEY(cid)
);

ALTER TABLE dt1
MODIFY COLUMN cid INT AUTO_INCREMENT;

ALTER TABLE dt1
ADD COLUMN cemail VARCHAR(50) UNIQUE NOT NULL;

SELECT *
FROM dt1;